# Generated by Django 3.0.7 on 2020-06-23 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('text', models.TextField(verbose_name='Bio')),
                ('picture', models.ImageField(default='default.png', upload_to='', verbose_name='Avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tytuł')),
                ('text', models.TextField(verbose_name='Treść')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia')),
                ('edited_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data edycji')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
