# Generated by Django 3.0.7 on 2020-07-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited_date',
            field=models.DateTimeField(verbose_name='Data edycji'),
        ),
        migrations.DeleteModel(
            name='Bio',
        ),
    ]
