# Generated by Django 3.0.7 on 2020-07-03 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200703_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data edycji'),
        ),
    ]
