# Generated by Django 3.0.7 on 2020-07-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200703_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='post',
            name='edited_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data edycji'),
        ),
    ]
